[package]
name = "megs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.15"
wasmer = "2.2.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
